name: Validate businesses.json

on:
  pull_request:
    paths:
      - 'data/businesses.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install jsonschema
        run: pip install jsonschema

      - name: Run validation script
        run: python scripts/validate.py

      - name: Inject API key into index.html
        run: |
          sed "s/__API_KEY__/${{ secrets.MAPS_API_KEY }}/g" index.template.html > index.html
